"""esquema inicial

Revision ID: 9491f0679771
Revises: 
Create Date: 2026-10-05 19:49:43.405297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9491f0679771'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polizas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('asegurado', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('prima', sa.Float(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('token_firma', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('predicciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poliza_id', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Float(), nullable=False),
    sa.Column('alto_riesgo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poliza_id'], ['polizas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siniestros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poliza_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['poliza_id'], ['polizas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siniestros')
    op.drop_table('predicciones')
    op.drop_table('polizas')
    # ### end Alembic commands ###
